<!DOCTYPE html>
<html lang="cs-cz">

<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title><?= $titulek ?></title>
    <meta name="description" content="<?= $popis ?>" />
    <meta name="keywords" content="<?= $klicova_slova ?>" />
    <link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>

    <header>
        <h1>Ukazkovy web</h1>
    </header>
    <?php foreach ($zpravy as $zprava) : ?>
    <p class="zprava"><?= $zprava ?></p>
    <?php endforeach ?>
    <nav>
        <ul>
            <li><a href="clanek/uvod">Uvod</a></li>
            <li><a href="clanek">Clanky</a></li>
            <li><a href="kontakt">Kontakt</a></li>
        </ul>
    </nav>

    <br clear="both" />

    <article>

        <?php $this->kontroler->vypisPohled(); ?>

    </article>

    <footer>

        <p>Ukazkovy tutorial pro jednoduche MVC</p>

    </footer>

</body>

</html>